name: Run Playwright & API Tests

on:
  workflow_dispatch:
    inputs:
      test_type:
        description: 'Tipo de tests a ejecutar'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - web_only
          - api_only
  push:
    branches: [ main, feature/test_api ]
  pull_request:
    branches: [ main ]

jobs:
  web-tests:
    runs-on: ubuntu-latest
    if: github.event.inputs.test_type == 'web_only' || github.event.inputs.test_type == 'all' || github.event_name == 'push' || github.event_name == 'pull_request'
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install --with-deps

      - name: Run Web Tests
        run: pytest tests/ -v --alluredir=allure-results

      - name: Generate Allure Report
        uses: simple-elf/allure-report-action@v1.6
        with:
          results-dir: allure-results
          report-dir: allure-report

      - name: Upload Allure Report (HTML)
        uses: actions/upload-artifact@v4
        with:
          name: allure-report-web
          path: allure-report/

  api-tests:
    runs-on: ubuntu-latest
    if: github.event.inputs.test_type == 'api_only' || github.event.inputs.test_type == 'all' || github.event_name == 'push' || github.event_name == 'pull_request'
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run API Tests
        run: pytest Api/test_api_tecnico.py -v --alluredir=allure-results-api

      - name: Generate Allure Report for API
        uses: simple-elf/allure-report-action@v1.6
        with:
          results-dir: allure-results-api
          report-dir: allure-report-api

      - name: Upload Allure Report API (HTML)
        uses: actions/upload-artifact@v4
        with:
          name: allure-report-api
          path: allure-report-api/ 